-- Cache columns for AI-generated content on shop listings.
-- ai_insight: market/investment insight generated by Claude with web search (refreshed every 7 days).
-- grade_analysis: PSA grade probability output for raw cards only (permanent once computed).

alter table public.shop_listings
  add column if not exists ai_insight       text          default null,
  add column if not exists ai_insight_at    timestamptz   default null,
  add column if not exists grade_analysis   jsonb         default null,
  add column if not exists grade_analysis_at timestamptz  default null;

comment on column public.shop_listings.ai_insight       is 'Cached AI market insight text (refreshed every 7 days).';
comment on column public.shop_listings.ai_insight_at    is 'Timestamp of last ai_insight generation.';
comment on column public.shop_listings.grade_analysis   is 'Cached grade probability JSON for raw/ungraded cards.';
comment on column public.shop_listings.grade_analysis_at is 'Timestamp of grade_analysis generation.';
